[33mWARNING [0m urllib3.connectionpool:connectionpool.py:868 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000020352970550>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/03b27b4751f586b5b76827627bb6bdd9/url
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:868 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000203529707D0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/03b27b4751f586b5b76827627bb6bdd9/url
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:868 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000203528D22C0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/03b27b4751f586b5b76827627bb6bdd9/url
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:868 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000203528EBCE0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/03b27b4751f586b5b76827627bb6bdd9
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:868 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000020352D6C050>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/03b27b4751f586b5b76827627bb6bdd9
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:868 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000020352D6C380>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/03b27b4751f586b5b76827627bb6bdd9